### PR TITLE
Calculate the light projection matrix analytically.

### PR DESCRIPTION
**Pull request by j9brown**
Derive the projection of the light from the orthographic projection
of the scene by applying a skew.  This makes the shadow map coincident
with the scene being rendered.

/cc @abarth

### CODE REVIEW

**Comment by abarth** [comment]
LGTM

Wonderful, thank you.

**Comment by abarth** [comment]
I'm going to land this so I can build on top of it.

**Comment by j9brown** [comment]
It occurs to me I missed a term in my matrix.  If the target ground plane
is at z=0 then everything is fine.  At other elevations we'll skew
improperly.  So we need to add a translation in x by target.z \* delta_x /
delta_z == target.z \* -skew_x.  Similarly in y.

**Comment by j9brown** [comment]
Incidentally, I found it helpful to imagine the effect of sunlight casting
a shadow off a vertical pole.  Since the light rays are parallel, the
displacement of the shadow can be described using similar triangles, which
is what leads to the skewed projection.

**Comment by abarth** [comment]
I'm actually experimenting with a screen-space approach at the moment, so don't stress too much about it.

**Comment by abarth** [comment]
Yeah, that's also what makes the screen space approach attractive.

**Comment by j9brown** [comment]
Which one are you looking at now?

**Comment by abarth** [comment]
http://graphics.cs.williams.edu/papers/SAOHPG12/McGuire12SAO-talk.pdf

**Comment by j9brown** [comment]
Interesting thought.  If the projection is orthographic and the scene is
only ever rendered from the camera viewpoint directly above (never
obliquely) then we may be able to apply the effect of displacement maps in
the fragment shader without having to construct any additional geometry.

**Comment by abarth** [comment]
Oh, neat idea.

**Comment by abarth** [comment]
At least for z displacements.

**Pull request merged**
