### PR TITLE
Add an iOS test harness

### PR DESCRIPTION
**Pull request by abarth**

### CODE REVIEW

**Comment by abarth** [comment]
@j9brown

**Comment by abarth** [comment]
BTW, I'm not happy with how this patch handles device scales.  I need to rework that part.

**Comment by j9brown** [comment]
lgtm but changes to test scenes will conflict

**Comment by abarth** [comment]
Go ahead and land your patch first.  I'd rebase on top of it.

**Comment by abarth** [comment]
I stripped this down to just what's needed to build.  I'll do the device scale stuff in another patch.

**Pull request merged**
